export const useStyles = makeStyles(theme => ({
  root: {
    '& > *': {
      margin: theme.spacing(1),
      width: '25ch',
    },
  },
  root2: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: theme.palette.background.paper,
  },
  whiteBox: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: 'white',
  },
  mainContainer: {
    marginLeft: 120,
    marginRight: 120,
    marginTop: 30,
    marginBottom: 50,
    height: '35vh',
    paddingLeft: 30,
    paddingRight: 30,
    paddingTop: 50,
    paddingBottom: 50,
  },
  leftBox: {
    width: '35vh',
    height: '1020px',
    backgroundColor: '#F5F5F5',
    float: 'left',
    paddingLeft: 10,
    paddingRight: 10,
    marginBottom: 100,
  },
  imgFloor1: {
    backgroundImage: 'url(' + 'http://localhost:3000/img/floor1.png' + ')',
    width: '700px',
    height: '499px',
    backgroundColor: '#EEE',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'center',
    float: 'right',
    paddingLeft: 20,
  },
  imgFloor2: {
    backgroundImage: 'url(' + 'http://localhost:3000/img/floor2.png' + ')',
    width: '700px',
    height: '499px',
    backgroundColor: '#EEE',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'center',
    float: 'right',
    paddingLeft: 20,
    marginTop: 20,
  },
}))
